package io.sniffy.sql;

import io.sniffy.Threads;
import io.sniffy.test.Count;

import java.lang.annotation.*;

/**
 * Adds an expectation about the number of queries generated by given test method
 * @since 3.1
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.ANNOTATION_TYPE})
@Inherited
public @interface SqlExpectation {

    /**
     * @return number of expected executed statements
     * since 3.1
     */
    Count count() default @Count;

    /**
     * @return number of expected affected or returned rows
     * since 3.1
     */
    Count rows() default @Count;

    /**
     * @return descriptor of which threads contribute to given expectation
     * @since 2.0
     */
    Threads threads() default Threads.CURRENT;

    /**
     * @return type of executed query
     * @since 2.2
     */
    SqlStatement query() default SqlStatement.ANY;

}