<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.sniffy</groupId>
        <artifactId>sniffy-integration-tests</artifactId>
        <version>4.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>sniffy-integration-tests-tomcat-10.1</artifactId>
    <name>Sniffy Tomcat 10.1 Servlet 6.0 Integration Tests</name>

    <dependencies>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
            <version>${tomcat.servlet6.version}</version>
        </dependency>
        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-integration-tests-tomcat-jakarta-support</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
