<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sniffy-parent</artifactId>
        <groupId>io.sniffy</groupId>
        <version>4.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sniffy-web</artifactId>

    <name>Sniffy Web</name>
    <url>http://sniffy.io/</url>
    <description>Sniffy Servlet integration for the Jakarta Servlet namespace</description>

    <build>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>../sniffy-web-common/src/main/resources</directory>
                <includes>
                    <include>io/sniffy/ui/**</include>
                </includes>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>ban-javax-servlet</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <bannedDependencies>
                                    <excludes>
                                        <exclude>javax.servlet:javax.servlet-api</exclude>
                                    </excludes>
                                    <searchTransitive>true</searchTransitive>
                                </bannedDependencies>
                            </rules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>check-signatures</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <phase>verify</phase>
                        <configuration>
                            <rules>
                                <checkSignatureRule implementation="org.codehaus.mojo.animal_sniffer.enforcer.CheckSignatureRule">
                                    <signature>
                                        <groupId>org.codehaus.mojo.signature</groupId>
                                        <artifactId>java18</artifactId>
                                        <version>1.0</version>
                                    </signature>
                                    <ignores>
                                        <ignore>java.nio.channels.AsynchronousSocketChannel</ignore>
                                        <ignore>java.nio.channels.spi.AsynchronousChannelProvider</ignore>
                                        <ignore>java.nio.channels.AsynchronousSocketChannel</ignore>
                                        <ignore>java.nio.channels.AsynchronousServerSocketChannel</ignore>
                                        <ignore>java.net.SocketOption</ignore>
                                        <ignore>java.net.StandardSocketOptions</ignore>
                                        <ignore>java.nio.channels.NetworkChannel</ignore>
                                        <ignore>java.nio.channels.AsynchronousChannelGroup</ignore>
                                        <ignore>sun.misc.Unsafe</ignore>
                                        <ignore>sun.nio.ch.DatagramChannelDelegate</ignore>
                                        <ignore>sun.nio.ch.ServerSocketChannelDelegate</ignore>
                                        <ignore>sun.nio.ch.SocketChannelDelegate</ignore>
                                    </ignores>
                                    <checkTestClasses>false</checkTestClasses>
                                </checkSignatureRule>
                                <checkSignatureRule implementation="org.codehaus.mojo.animal_sniffer.enforcer.CheckSignatureRule">
                                    <signature>
                                        <groupId>org.codehaus.mojo.signature</groupId>
                                        <artifactId>java17</artifactId>
                                        <version>1.0</version>
                                    </signature>
                                    <ignores>
                                        <ignore>sun.nio.ch.SelChImpl</ignore>
                                        <ignore>sun.misc.Unsafe</ignore>
                                        <ignore>sun.nio.ch.DatagramChannelDelegate</ignore>
                                        <ignore>sun.nio.ch.ServerSocketChannelDelegate</ignore>
                                        <ignore>sun.nio.ch.SocketChannelDelegate</ignore>
                                    </ignores>
                                    <checkTestClasses>false</checkTestClasses>
                                </checkSignatureRule>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>



        </plugins>
    </build>

    <dependencies>

        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-web-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-module-tls</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-module-nio</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-core</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>${jakarta.servlet.version}</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>
</project>
