<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.sniffy</groupId>
        <artifactId>sniffy-integration-tests</artifactId>
        <version>3.2.0-SNAPSHOT</version>
    </parent>

    <artifactId>sniffy-integration-tests-servlet-contract</artifactId>
    <name>Sniffy Servlet Namespace Contract Tests</name>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-servlet-artifacts</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeGroupIds>io.sniffy</includeGroupIds>
                            <includeArtifactIds>sniffy-web,sniffy-web-javax,sniffy-spring,sniffy-spring-javax</includeArtifactIds>
                            <outputDirectory>${project.build.directory}/artifacts</outputDirectory>
                            <excludeTransitive>true</excludeTransitive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-web</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-web-javax</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-spring</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-spring-javax</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>9.8</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
