package io.sniffy;

import io.sniffy.junit.QueryCounter;
import io.sniffy.test.Count;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Adds an expectation about the number of queries generated by given test method
 * @see QueryCounter
 * @since 2.0
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.ANNOTATION_TYPE})
public @interface Expectation {

    /**
     * @since 2.0
     */
    @Deprecated
    int value() default -1;

    /**
     * @since 2.0
     */
    @Deprecated
    int atMost() default -1;

    /**
     * @since 2.0
     */
    @Deprecated
    int atLeast() default -1;

    /**
     * since 3.1
     */
    Count count() default @Count;

    /**
     * @since 2.0
     */
    Threads threads() default Threads.CURRENT;

    /**
     * @since 2.2
     */
    Query query() default Query.ANY;

}