package io.sniffy.socket;

import io.sniffy.test.Count;
import io.sniffy.Threads;
import io.sniffy.junit.QueryCounter;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Adds an expectation about the number of queries generated by given test method
 * @see QueryCounter
 * @since 3.1
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.ANNOTATION_TYPE})
public @interface SocketExpectation {

    /*int port() default -1;*/

    String hostName() default "";

    Count connections() default @Count;

    /*Count bytesUp();

    Count bytesDown();

    Count bytsTotal();*/

    /**
     * @since 3.1
     */
    Threads threads() default Threads.CURRENT;

}