package io.sniffy.socket;

import io.sniffy.Threads;
import io.sniffy.test.Count;

import java.lang.annotation.*;

/**
 * Adds an expectation about the number of queries generated by given test method
 * @see SniffyRule
 * @since 3.1
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.ANNOTATION_TYPE})
@Inherited
public @interface SocketExpectation {

    /*int port() default -1;*/

    String hostName() default "";

    Count connections() default @Count;

    /*Count bytesUp();

    Count bytesDown();

    Count bytesTotal();*/

    /**
     * @since 3.1
     */
    Threads threads() default Threads.CURRENT;

}