package com.github.bedrin.jdbc.sniffer.junit;

import com.github.bedrin.jdbc.sniffer.Query;
import com.github.bedrin.jdbc.sniffer.Threads;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Adds an expectation about the number of queries generated by given test method
 * @see QueryCounter
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.ANNOTATION_TYPE})
public @interface Expectation {

    int value() default -1;
    int atMost() default -1;
    int atLeast() default -1;

    Threads threads() default Threads.CURRENT;
    Query query() default Query.ANY;

}