package io.sniffy.sql;

import io.sniffy.Query;
import io.sniffy.Threads;
import io.sniffy.test.Count;
import io.sniffy.test.junit.SniffyRule;

import java.lang.annotation.*;

/**
 * Adds an expectation about the number of queries generated by given test method
 * @see SniffyRule
 * @since 2.0
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.ANNOTATION_TYPE})
@Inherited
public @interface SqlExpectation {

    /**
     * since 3.1
     */
    Count count() default @Count;

    /**
     * since 3.1
     */
    Count rows() default @Count;

    /**
     * @since 2.0
     */
    Threads threads() default Threads.CURRENT;

    /**
     * @since 2.2
     */
    Query query() default Query.ANY;

}