<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.sniffy</groupId>
        <artifactId>sniffy-parent</artifactId>
        <version>3.2.0-SNAPSHOT</version>
    </parent>

    <artifactId>sniffy-web-common</artifactId>
    <name>Sniffy Web Common</name>
    <description>Namespace-neutral internal support for Sniffy Servlet integrations</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <testSource>1.8</testSource>
                    <testTarget>1.8</testTarget>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.sniffy</groupId>
            <artifactId>sniffy-core</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
