FROM maven:3.8.4-openjdk-17

ADD . /usr/src/mymaven

ADD ./repository $MAVEN_CONFIG/repository

RUN cd /usr/src/mymaven && \
    mvn -v && \
    mvn -B -f sniffy-compatibility-tests/pom.xml -P qemu test || mvn -B -f pom.xml -P qemu test